/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as Char43notFoundRouteImport } from './routes/+not-found'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedBuyPremiumRouteImport } from './routes/_authenticated/buy-premium'
import { Route as AuthenticatedAddTransactionRouteImport } from './routes/_authenticated/add-transaction'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedTransactionIdRouteImport } from './routes/_authenticated/transaction.$id'
import { Route as AuthenticatedProfileSettingsRouteImport } from './routes/_authenticated/profile/settings'
import { Route as AuthenticatedProfilePersonalInfoRouteImport } from './routes/_authenticated/profile/personal-info'
import { Route as AuthenticatedProfileMembershipRouteImport } from './routes/_authenticated/profile/membership'
import { Route as AuthenticatedProfileCategoriesRouteImport } from './routes/_authenticated/profile/categories'
import { Route as AuthenticatedEditIdRouteImport } from './routes/_authenticated/edit.$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const Char43notFoundRoute = Char43notFoundRouteImport.update({
  id: '/+not-found',
  path: '/+not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuyPremiumRoute = AuthenticatedBuyPremiumRouteImport.update({
  id: '/buy-premium',
  path: '/buy-premium',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddTransactionRoute =
  AuthenticatedAddTransactionRouteImport.update({
    id: '/add-transaction',
    path: '/add-transaction',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionIdRoute =
  AuthenticatedTransactionIdRouteImport.update({
    id: '/transaction/$id',
    path: '/transaction/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileSettingsRoute =
  AuthenticatedProfileSettingsRouteImport.update({
    id: '/profile/settings',
    path: '/profile/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilePersonalInfoRoute =
  AuthenticatedProfilePersonalInfoRouteImport.update({
    id: '/profile/personal-info',
    path: '/profile/personal-info',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileMembershipRoute =
  AuthenticatedProfileMembershipRouteImport.update({
    id: '/profile/membership',
    path: '/profile/membership',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileCategoriesRoute =
  AuthenticatedProfileCategoriesRouteImport.update({
    id: '/profile/categories',
    path: '/profile/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEditIdRoute = AuthenticatedEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/+not-found': typeof Char43notFoundRoute
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/add-transaction': typeof AuthenticatedAddTransactionRoute
  '/buy-premium': typeof AuthenticatedBuyPremiumRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
  '/profile/categories': typeof AuthenticatedProfileCategoriesRoute
  '/profile/membership': typeof AuthenticatedProfileMembershipRoute
  '/profile/personal-info': typeof AuthenticatedProfilePersonalInfoRoute
  '/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/transaction/$id': typeof AuthenticatedTransactionIdRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/+not-found': typeof Char43notFoundRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/add-transaction': typeof AuthenticatedAddTransactionRoute
  '/buy-premium': typeof AuthenticatedBuyPremiumRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/': typeof AuthenticatedIndexRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
  '/profile/categories': typeof AuthenticatedProfileCategoriesRoute
  '/profile/membership': typeof AuthenticatedProfileMembershipRoute
  '/profile/personal-info': typeof AuthenticatedProfilePersonalInfoRoute
  '/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/transaction/$id': typeof AuthenticatedTransactionIdRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/+not-found': typeof Char43notFoundRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/add-transaction': typeof AuthenticatedAddTransactionRoute
  '/_authenticated/buy-premium': typeof AuthenticatedBuyPremiumRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/edit/$id': typeof AuthenticatedEditIdRoute
  '/_authenticated/profile/categories': typeof AuthenticatedProfileCategoriesRoute
  '/_authenticated/profile/membership': typeof AuthenticatedProfileMembershipRoute
  '/_authenticated/profile/personal-info': typeof AuthenticatedProfilePersonalInfoRoute
  '/_authenticated/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/_authenticated/transaction/$id': typeof AuthenticatedTransactionIdRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/+not-found'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/add-transaction'
    | '/buy-premium'
    | '/statistics'
    | '/edit/$id'
    | '/profile/categories'
    | '/profile/membership'
    | '/profile/personal-info'
    | '/profile/settings'
    | '/transaction/$id'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/+not-found'
    | '/sign-in'
    | '/sign-up'
    | '/add-transaction'
    | '/buy-premium'
    | '/statistics'
    | '/'
    | '/edit/$id'
    | '/profile/categories'
    | '/profile/membership'
    | '/profile/personal-info'
    | '/profile/settings'
    | '/transaction/$id'
    | '/profile'
  id:
    | '__root__'
    | '/+not-found'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/add-transaction'
    | '/_authenticated/buy-premium'
    | '/_authenticated/statistics'
    | '/_authenticated/'
    | '/_authenticated/edit/$id'
    | '/_authenticated/profile/categories'
    | '/_authenticated/profile/membership'
    | '/_authenticated/profile/personal-info'
    | '/_authenticated/profile/settings'
    | '/_authenticated/transaction/$id'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char43notFoundRoute: typeof Char43notFoundRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/+not-found': {
      id: '/+not-found'
      path: '/+not-found'
      fullPath: '/+not-found'
      preLoaderRoute: typeof Char43notFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buy-premium': {
      id: '/_authenticated/buy-premium'
      path: '/buy-premium'
      fullPath: '/buy-premium'
      preLoaderRoute: typeof AuthenticatedBuyPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-transaction': {
      id: '/_authenticated/add-transaction'
      path: '/add-transaction'
      fullPath: '/add-transaction'
      preLoaderRoute: typeof AuthenticatedAddTransactionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transaction/$id': {
      id: '/_authenticated/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/transaction/$id'
      preLoaderRoute: typeof AuthenticatedTransactionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/settings': {
      id: '/_authenticated/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof AuthenticatedProfileSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/personal-info': {
      id: '/_authenticated/profile/personal-info'
      path: '/profile/personal-info'
      fullPath: '/profile/personal-info'
      preLoaderRoute: typeof AuthenticatedProfilePersonalInfoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/membership': {
      id: '/_authenticated/profile/membership'
      path: '/profile/membership'
      fullPath: '/profile/membership'
      preLoaderRoute: typeof AuthenticatedProfileMembershipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/categories': {
      id: '/_authenticated/profile/categories'
      path: '/profile/categories'
      fullPath: '/profile/categories'
      preLoaderRoute: typeof AuthenticatedProfileCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edit/$id': {
      id: '/_authenticated/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof AuthenticatedEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAddTransactionRoute: typeof AuthenticatedAddTransactionRoute
  AuthenticatedBuyPremiumRoute: typeof AuthenticatedBuyPremiumRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEditIdRoute: typeof AuthenticatedEditIdRoute
  AuthenticatedProfileCategoriesRoute: typeof AuthenticatedProfileCategoriesRoute
  AuthenticatedProfileMembershipRoute: typeof AuthenticatedProfileMembershipRoute
  AuthenticatedProfilePersonalInfoRoute: typeof AuthenticatedProfilePersonalInfoRoute
  AuthenticatedProfileSettingsRoute: typeof AuthenticatedProfileSettingsRoute
  AuthenticatedTransactionIdRoute: typeof AuthenticatedTransactionIdRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddTransactionRoute: AuthenticatedAddTransactionRoute,
  AuthenticatedBuyPremiumRoute: AuthenticatedBuyPremiumRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEditIdRoute: AuthenticatedEditIdRoute,
  AuthenticatedProfileCategoriesRoute: AuthenticatedProfileCategoriesRoute,
  AuthenticatedProfileMembershipRoute: AuthenticatedProfileMembershipRoute,
  AuthenticatedProfilePersonalInfoRoute: AuthenticatedProfilePersonalInfoRoute,
  AuthenticatedProfileSettingsRoute: AuthenticatedProfileSettingsRoute,
  AuthenticatedTransactionIdRoute: AuthenticatedTransactionIdRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  Char43notFoundRoute: Char43notFoundRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
