/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as Char43notFoundRouteImport } from './routes/+not-found'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedPersonalInfoRouteImport } from './routes/_authenticated/personal-info'
import { Route as AuthenticatedDebtsRouteImport } from './routes/_authenticated/debts'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedAddTransactionRouteImport } from './routes/_authenticated/add-transaction'
import { Route as AuthenticatedAddDebtRouteImport } from './routes/_authenticated/add-debt'
import { Route as AuthenticatedTransactionIdRouteImport } from './routes/_authenticated/transaction.$id'
import { Route as AuthenticatedEditIdRouteImport } from './routes/_authenticated/edit.$id'
import { Route as AuthenticatedDebtIdRouteImport } from './routes/_authenticated/debt.$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const Char43notFoundRoute = Char43notFoundRouteImport.update({
  id: '/+not-found',
  path: '/+not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPersonalInfoRoute =
  AuthenticatedPersonalInfoRouteImport.update({
    id: '/personal-info',
    path: '/personal-info',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDebtsRoute = AuthenticatedDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddTransactionRoute =
  AuthenticatedAddTransactionRouteImport.update({
    id: '/add-transaction',
    path: '/add-transaction',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAddDebtRoute = AuthenticatedAddDebtRouteImport.update({
  id: '/add-debt',
  path: '/add-debt',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionIdRoute =
  AuthenticatedTransactionIdRouteImport.update({
    id: '/transaction/$id',
    path: '/transaction/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEditIdRoute = AuthenticatedEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDebtIdRoute = AuthenticatedDebtIdRouteImport.update({
  id: '/debt/$id',
  path: '/debt/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/+not-found': typeof Char43notFoundRoute
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/add-debt': typeof AuthenticatedAddDebtRoute
  '/add-transaction': typeof AuthenticatedAddTransactionRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/debts': typeof AuthenticatedDebtsRoute
  '/personal-info': typeof AuthenticatedPersonalInfoRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/debt/$id': typeof AuthenticatedDebtIdRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
  '/transaction/$id': typeof AuthenticatedTransactionIdRoute
}
export interface FileRoutesByTo {
  '/+not-found': typeof Char43notFoundRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/add-debt': typeof AuthenticatedAddDebtRoute
  '/add-transaction': typeof AuthenticatedAddTransactionRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/debts': typeof AuthenticatedDebtsRoute
  '/personal-info': typeof AuthenticatedPersonalInfoRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/': typeof AuthenticatedIndexRoute
  '/debt/$id': typeof AuthenticatedDebtIdRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
  '/transaction/$id': typeof AuthenticatedTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/+not-found': typeof Char43notFoundRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/add-debt': typeof AuthenticatedAddDebtRoute
  '/_authenticated/add-transaction': typeof AuthenticatedAddTransactionRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/debts': typeof AuthenticatedDebtsRoute
  '/_authenticated/personal-info': typeof AuthenticatedPersonalInfoRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/debt/$id': typeof AuthenticatedDebtIdRoute
  '/_authenticated/edit/$id': typeof AuthenticatedEditIdRoute
  '/_authenticated/transaction/$id': typeof AuthenticatedTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/+not-found'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/add-debt'
    | '/add-transaction'
    | '/categories'
    | '/debts'
    | '/personal-info'
    | '/statistics'
    | '/debt/$id'
    | '/edit/$id'
    | '/transaction/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/+not-found'
    | '/sign-in'
    | '/sign-up'
    | '/add-debt'
    | '/add-transaction'
    | '/categories'
    | '/debts'
    | '/personal-info'
    | '/statistics'
    | '/'
    | '/debt/$id'
    | '/edit/$id'
    | '/transaction/$id'
  id:
    | '__root__'
    | '/+not-found'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/add-debt'
    | '/_authenticated/add-transaction'
    | '/_authenticated/categories'
    | '/_authenticated/debts'
    | '/_authenticated/personal-info'
    | '/_authenticated/statistics'
    | '/_authenticated/'
    | '/_authenticated/debt/$id'
    | '/_authenticated/edit/$id'
    | '/_authenticated/transaction/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char43notFoundRoute: typeof Char43notFoundRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/+not-found': {
      id: '/+not-found'
      path: '/+not-found'
      fullPath: '/+not-found'
      preLoaderRoute: typeof Char43notFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal-info': {
      id: '/_authenticated/personal-info'
      path: '/personal-info'
      fullPath: '/personal-info'
      preLoaderRoute: typeof AuthenticatedPersonalInfoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/debts': {
      id: '/_authenticated/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AuthenticatedDebtsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-transaction': {
      id: '/_authenticated/add-transaction'
      path: '/add-transaction'
      fullPath: '/add-transaction'
      preLoaderRoute: typeof AuthenticatedAddTransactionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-debt': {
      id: '/_authenticated/add-debt'
      path: '/add-debt'
      fullPath: '/add-debt'
      preLoaderRoute: typeof AuthenticatedAddDebtRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transaction/$id': {
      id: '/_authenticated/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/transaction/$id'
      preLoaderRoute: typeof AuthenticatedTransactionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edit/$id': {
      id: '/_authenticated/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof AuthenticatedEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/debt/$id': {
      id: '/_authenticated/debt/$id'
      path: '/debt/$id'
      fullPath: '/debt/$id'
      preLoaderRoute: typeof AuthenticatedDebtIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAddDebtRoute: typeof AuthenticatedAddDebtRoute
  AuthenticatedAddTransactionRoute: typeof AuthenticatedAddTransactionRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDebtsRoute: typeof AuthenticatedDebtsRoute
  AuthenticatedPersonalInfoRoute: typeof AuthenticatedPersonalInfoRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDebtIdRoute: typeof AuthenticatedDebtIdRoute
  AuthenticatedEditIdRoute: typeof AuthenticatedEditIdRoute
  AuthenticatedTransactionIdRoute: typeof AuthenticatedTransactionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddDebtRoute: AuthenticatedAddDebtRoute,
  AuthenticatedAddTransactionRoute: AuthenticatedAddTransactionRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDebtsRoute: AuthenticatedDebtsRoute,
  AuthenticatedPersonalInfoRoute: AuthenticatedPersonalInfoRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDebtIdRoute: AuthenticatedDebtIdRoute,
  AuthenticatedEditIdRoute: AuthenticatedEditIdRoute,
  AuthenticatedTransactionIdRoute: AuthenticatedTransactionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  Char43notFoundRoute: Char43notFoundRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
